name: Daily Fofa Search

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      query:
        description: "Fofa 查询语句"
        required: true
        default: 'server=="cloudflare" && port=="443" && header="Forbidden" && country=="US" && asn!="13335" && asn!="209242"'
      days:
        description: "时间范围 (单位: 天)"
        required: false
        default: 30
      output:
        description: "输出文件名"
        required: false
        default: "ip.txt"

jobs:
  fofa-search:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Debugging
      run: |
        echo "Running with query: ${{ inputs.query }}"
        echo "Output file: ${{ inputs.output }}"

    - name: Run Fofa script
      run: |
        python fofa_search.py --query="${{ inputs.query }}" --days=${{ inputs.days }} --output="${{ inputs.output }}"

    - name: Upload output file
      uses: actions/upload-artifact@v3
      with:
        name: ip-list
        path: ${{ inputs.output }}
