name: Daily Task

on:
  schedule:
    # 每天运行两次，间隔12小时
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  daily-task:
    runs-on: ubuntu-latest

    steps:
    # 检出仓库代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # 运行 Python 脚本
    - name: Run Python script
      run: python nwe.py

    # 提交生成的文件
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add *.m3u *.txt
        git commit -m "Update playlist and results"
        git push
