name: Run Script Every 6 Hours

on:
  schedule:
    - cron: '0 */6 * * *'  # 每 6 小时运行一次
  workflow_dispatch:       # 手动触发选项

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run the script
        run: |
          chmod +x /path/to/your/script.sh
          /path/to/your/script.sh
